### PR TITLE
Increase coverage

### LINKED ISSUE #23: Open tools from results, not only their class
As a user when I search for the name of a tool I want to be able to open that tool and not only its claas definition in order to use Algernon as a general purpose launcher.

# Acceptance Criteria
- [x] the `open` hotword can directly open a tool (rather than its class) additionally to it's existing functionality of opening Apps
  - A tool is any program listed in the Tools dropdown

# Old description
Algernon should also allow developers to open tools directly from the launcher (Browser, Workspace, Transcript, ...)

### LINKED ISSUE #45: Code Coverage too low
I'm currently trying to figure out how to include coverage results in our CI pipeline. While doing that I noticed that the coverage hovers around 83%. Which is not nearly acceptable. I would aim for at least 95%. That's around the percentage where we can really start relying on our tests.

You can have a look yourself at https://coveralls.io/github/hpi-swa-teaching/Algernon-Launcher?branch=development.

Any thoughts? How would you prioritize this?

### PR DESCRIPTION
**Pull request by BenBalsInsecure**

### CODE REVIEW

**Comment by BenBals** [comment]
I have not yet written as much tests as I would like, but I would appreciate having the tests inside development so they can serve for further code.

@sinnaj-r

**Comment by BenBals** [comment]
This branch may only be merged after #58, because I merged that branch to keep test helpers consistent.

**Comment by BenBals** [comment]
TODO
- [x] Find a way to close a Repository Browser.

**Comment by BenBals** [comment]
`MCWorkingCopyBrowser>>close` does not close the Monticello Browser.

I have tried to find a way for about half an hour now. Any ideas, @sinnaj-r?

**Comment by BenBals** [comment]
I have found a hacky way to close the browsers, but I have built a fairly nice abstraction around it.

You can use `findPluggableSystemWindowsByLabel:` and `deleteNewPluggableSystemWindowsByLabel:old:` to achieve that behavior.

**Comment by BenBals** [comment]
The test coverage is up to 86%.

**Comment by BenBals** [comment]
Coverage: 87%.

**Comment by BenBals** [comment]
Code Coverage: 89%.

**Comment by BenBals** [comment]
Closes #23.

**Comment by BenBals** [comment]
Code Coverage: 90%.

**Comment by BenBals** [comment]
As the coverage has reached 90%, I think we should merge this pr.

(But only after #58, as I already said.)

**Review by sinnaj-r — APPROVED** [review]

**Pull request merged**
