### PR TITLE
Directly search for methods, #19

### PR DESCRIPTION
**Pull request by BenBals**
NB. that currently we do not recommend merging this PR. It makes Algernon noticeably slower because we add about 70'000 items to search through. That can only be mitigated by solving #56 and #1.

### CODE REVIEW

**Comment by BenBals** [comment]
@MrModder how do you feel about the speed trade-off?

You could take a look at my proposal in #56. If you like that behavior, we could to a spike to see if it mitigates the speed problems.

**Comment by LeonMatthes** [comment]
### Customer feedback
The lag in my image doesn't seem too bad, it's somewhat noticeable, but could be worse.
Further performance optimizations can be handled as User stories (with spikes as necessary).

### Tutor feedback
As developers, taking care to not degrade performance to the point of unusability is your own responsibility, and you are free to make whatever changes necessary. Take care to consider this when estimating a User Stories effort.
Small degradations like these are acceptable, however.

**Review by kej-jay — CHANGES_REQUESTED** [review]
Test ran through, manual testing worked well too and coverage is not lower than the value I knew of. 
Good job you both.

One single thing that is not causing any crashes or so, but if you'd explain it to me if you know why this is happening:
The debug console opens up when running the tests and gives the following errors:
_LoadLibrary(UUIDPlugin) (998: Unzuläÿssiger Zugriff auf einen Speicherbereich.)
LoadLibrary(UUIDPlugin.dll) (998: Unzuläÿssiger Zugriff auf einen Speicherbereich.)
LoadLibrary(SqueakSSL) (998: Unzuläÿssiger Zugriff auf einen Speicherbereich.)
LoadLibrary(SqueakSSL.dll) (998: Unzuläÿssiger Zugriff auf einen Speicherbereich.)_

Again, no tests crashed because of this, but it seems suspicious to me, so I wanted to ask you, if you have a clue what it is about.

**Comment by BenBals** [comment]
I have no idea what that is about. I cannot see how that is related to our changes.

Do you see similar behavior on other branches?

Could you provide the stack trace from the debugger?

**Comment by BenBals** [comment]
@kej-jay have you found out if your issue is related to this pr?

**Comment by kej-jay** [comment]
> 
> 
> @kej-jay have you found out if your issue is related to this pr?

Yes, a clean install stopped it from happening, so I guess my image was causing this.

**Review by kej-jay — APPROVED** [review]

**Review by robertkirsten — APPROVED** [review]
Looks good from my point of view too, all tests passed, code coverage was increased and searching for methods works very good!

**Pull request merged**
