### PR TITLE
fixed the minor linting issues

### PR DESCRIPTION
**Pull request by kej-jay**
The one questionable message was not so questionable in my opinion, so it has been left in. Please let me knwo if you are on the linters side and think it is questionable or if you agree.

### CODE REVIEW

**Review by BenBals — CHANGES_REQUESTED** [review]
First off: Good job.

I do find the message questionable. I think it refers to this line: 

```smalltalk
	detect: [ :w | w model isKindOf: SystemBrowser default ]
```

and to the `isKindOf:` in particular. This is meta-programming and should be avoided. Please try something like this test code:

```smalltalk
	detect: [:each | each knownName asLowercase includesSubstring: 'System Browser' ]
```

**Review by BenBals — APPROVED** [review]
Looks good to me. Just ignore the failing test on macos. I've another PR ongoing for that #156. Please resolve the merge conflict.

**Comment by kej-jay** [comment]
@BenBals @sinnaj-r Any idea regarding the merge conflict? It is literaly just normal changes that need to be made for the linter. Any help would be appreciated

**Comment by BenBals** [comment]
Just merge dev into this branch manually using the git browser and see what comes up.

**Review by sinnaj-r — APPROVED** [review]

**Comment by kej-jay** [comment]
@BenBals I fixed the merge conflict, it was because philip deleted that class. Once the tests pass, I will merge into development

**Pull request merged**
