### PR TITLE
Rewrite Cleanup

### LINKED ISSUE #119: Rewrite Clean up

### PR DESCRIPTION
**Pull request by BenBals**
# Please do the following to test before you approve.

1. Check out master using the Git Browser.
1. Run `ALGInstallation instance cleanup` to reset Algernon to the master version.
1. Use Algernon by running a few example queries of your choosing. Confirm that the Algernon looks old.
1. Run the upgrade snippet below.
	```smalltalk
	BaselineOfAlgernon compile: 'projectClass ^ Smalltalk at: #MetacelloCypressBaselineProject ifAbsent: 	[super projectClass]'.
	[ Metacello new
    baseline: 'Algernon';
    repository: 'github://HPI-SWA-Teaching/Algernon-Launcher:cleanup/packages';
    onConflictUseIncoming;   
	get;
    load. ] on: MetacelloSkipDirtyPackageLoad do: [:ex | ex resume: false. ].
	```
1. No errors may appear during the upgrade, except merge errors like [1].
1. Test that Algernon still works by running a few example queries of your choosing.

## Repeat the same process for `development`
The process is the same, but for two changes:
- checkout `development` in step 1
- use following snippet in step 4 instead.
```smalltalk
 Metacello new
       baseline: 'Algernon';
       repository: 'github://HPI-SWA-Teaching/Algernon-Launcher:cleanup/packages';
       onConflict: [:ex | ex allow];
       load
```

[1] Merge error that is okay during the upgrade. This error may appear for each package of `Algernon`, `AlgernonTests`, `BaselineOfAlgernon`. 
> You are about to load new versions of the following packages that have unsaved changes in the image.  If you continue, you will lose these changes.
> Algernon

### CODE REVIEW

**Comment by BenBals** [comment]
@MrModder (Tutor) I have a question regarding Baselines. Then I'm on master and I do

```smalltalk
 Metacello new
       baseline: 'Algernon';
       repository: 'github://HPI-SWA-Teaching/Algernon-Launcher:cleanup/packages';
       onConflict: [:ex | ex allow];
       load
```

the `postLoad` is not run and I can't even find it in the code browser even though it's in the `cleanup` branch. Do you have any idea why that could be? It only appears after I checkout the code via the git browser.

**Comment by kej-jay** [comment]
I encountered not only the in [1] mentioned error, but had the same warning for BaselineOfAlgernon and AlgernonTests.  

I do not know wheather this is caused by the software or if I did not follow the instructions correctly. @BenBals If you ask me, the instructions are not very clear (or I didnt get them ^^). My recommendations/questions for the instruction are listed below, I will gladly test the steps again.  

- mention to checkout master/dev through the git Brower(at least I did forget this the first time)
- Please ellaborate on "use algernon", just use it anyhow and test a single word or so?
- split step 5 in two and make the step to check for errors first, the test algernon. And while doing so, maybe specify "test" (UAT or running tests? What is expected to be tested? Where do you expect failures and therefore where should we put the finger in the wound?)
- For the repetition I was unsure about the snippet. I just used that snippet instead of the one specified above, but I wasnt sure if i was supposed to run the "old" snippet first and run the new snippet afterwards.  

As I said, I will gladly test again, but I think I am not on the same level as that I can fulfill your testing the way you want right now.

**Comment by sinnaj-r** [comment]
When running on master I get the Pop-Up with [1] 3 times, running on dev I get it 2 times. But that ain't a big problem imho. 
In both cases Algernon runs fine and I get no additional errors.

**Review by sinnaj-r — APPROVED** [review]

**Comment by BenBals** [comment]
> When running on master I get the Pop-Up with [1] 3 times, running on dev I get it 2 times. But that ain't a big problem imho.
In both cases Algernon runs fine and I get no additional errors.

This is the expected behavior. The reason is that compared to master the ``BaselineOfAlgernon`` package was changed, but those changes are already in dev.

**Comment by BenBals** [comment]
@kej-jay Thanks for your feedback! I've updated the instructions accordingly. Please test again and let me know if anything is unclear.

**Comment by kej-jay** [comment]
Tested again. For master I got Baseline.., AlgernonTest and Algernon warnings each once, but that shouldn't be a problem. When on dev I did not have any warnings.

**Review by kej-jay — APPROVED** [review]

**Comment by BenBals** [comment]
Awesome, thanks for your review, guys. I really want to get this right, so I appreciate your input.

**Review by robertkirsten — APPROVED** [review]

**Review by phlprcks — APPROVED** [review]

**Pull request merged**
