### PR TITLE
Remove Dependency on SWALint Outside of Testing

### LINKED ISSUE #143: Installation in Squeak 5.3 emits deprecation warning
When Upgrading to a new Algernon Version in Squeak with the provided Snippet (as created in #125 ), you have to dismiss ~20 Deprecation Warnings.

### PR DESCRIPTION
**Pull request by BenBals**
Fixes #143 

Please try again with this version, @sinnaj-r.

### CODE REVIEW

**Comment by sinnaj-r** [comment]
> Fixes #143
> 
> Please try again with this version, @sinnaj-r.

Thank you, I will try once the smalltalkhub.com Servers are online again. 
(And allow me to install Metacello on my fresh image) ...

**Comment by BenBals** [comment]
Is smalltalkhub back up again? I can ping it, but the website does not load. The missing web ui seems to be on purpose according to some mailing list entries.

**Comment by sinnaj-r** [comment]
> Is smalltalkhub back up again? I can ping it, but the website does not load. The missing web ui seems to be on purpose according to some mailing list entries.

At least on my machines I can't install Metacello on an fresh Squeak Image.

I get stuck here:

Screen Shot 2020-08-04 at 3 22 09 PM


Maybe @phlprcks, @kej-jay or @robertkirsten can confirm ?
(Steps: Download Squeak from Website for your platform; In the Setup-"Popup" tick the Git Support-Checkbox, run the Installation)

**Comment by phlprcks** [comment]
> 
> 
> > Is smalltalkhub back up again? I can ping it, but the website does not load. The missing web ui seems to be on purpose according to some mailing list entries.
> 
> At least on my machines I can't install Metacello on an fresh Squeak Image.
> 
> I get stuck here:
> 
> Screen Shot 2020-08-04 at 3 22 09 PM
> 
> Maybe @phlprcks, @kej-jay or @robertkirsten can confirm ?
> (Steps: Download Squeak from Website for your platform; In the Setup-"Popup" tick the Git Support-Checkbox, run the Installation)

I am stuck (probably) at the same point, however the error message suggests that there is a load conflict with the existing BaselineOfSton

Is that the same error you were receiving, @sinnaj-r ?
image

**Comment by robertkirsten** [comment]
> > > Is smalltalkhub back up again? I can ping it, but the website does not load. The missing web ui seems to be on purpose according to some mailing list entries.
...
> Is that the same error you were receiving, @sinnaj-r ?
> image

I have the same problem as @phlprcks.

**Comment by sinnaj-r** [comment]
Please install the SWALint only when it's needed in Postload:
https://github.com/hpi-swa-teaching/Algernon-Launcher/blob/ed898cd371d77a446fde60754a05234cbd33303a/packages/BaselineOfAlgernon.package/BaselineOfAlgernon.class/instance/postLoad.st#L3

(Or if the  #SwaLint Global exists)

**Comment by sinnaj-r** [comment]
> Please install the SWALint only when it's needed in Postload:
> 
> https://github.com/hpi-swa-teaching/Algernon-Launcher/blob/ed898cd371d77a446fde60754a05234cbd33303a/packages/BaselineOfAlgernon.package/BaselineOfAlgernon.class/instance/postLoad.st#L3

Apart from that when I e.g. comment out that line it's working and I get no deprecation warning 👍

**Review by sinnaj-r — APPROVED** [review]

**Pull request merged**
