### PR TITLE
Make COVERALLS_REPO_TOKEN secret available

### PR DESCRIPTION
**Pull request by fniephaus**
This allows smalltalkCI to upload coverage reports to Coveralls from GitHub actions (example is at [1]). Unfortunately, Coveralls does not seem to support GitHub actions properly yet (the integration is limited to lcov files), but using a repo_token (see [2]) it is possible to upload coverage results in Coveralls' raw JSON format.

[1] https://coveralls.io/jobs/65929250
[2] https://docs.coveralls.io/api-introduction

### CODE REVIEW

**Comment by BenBals** [comment]
Thank you very much! Seems to work.

Do you have the permission to set the coveralls app to post statistics on every pull request?

**Comment by fniephaus** [comment]
> Do you have the permission to set the coveralls app to post statistics on every pull request?

Yes, but it's already enabled.

**Comment by BenBals** [comment]
Hmm, do you have any idea why it doesn't show up then?

**Comment by fniephaus** [comment]
Nothing shows up on this PR because it's introducing code coverage. Let me know if it doesn't work on new PRs

**Pull request merged**
