### PR TITLE
Better Coverage Integration

### LINKED ISSUE #32: Setup GitHub Actions
As a contributor I want to see whether may changes make the tests fail in order to keep up the code quality.

To be compliant with the software development process outlined in the introductory lecture, we will use GitHub Actions for CI/CD.

This needs to be set up.

### PR DESCRIPTION
**Pull request by BenBalsInsecure**

### CODE REVIEW

**Comment by BenBals** [comment]
Related to https://github.com/hpi-swa/smalltalkCI/issues/458

**Comment by BenBals** [comment]
One example might be https://github.com/ba-st/Buoy/blob/release-candidate/.github/workflows/build.yml

**Comment by BenBals** [comment]
I have tried to copy that example. The Actions say that the upload was successful. Let's see.

**Comment by BenBals** [comment]
Coverage reports are supposedly uploaded fine but can not be retrieved on the codecov website. See https://codecov.io/github/hpi-swa-teaching/Algernon-Launcher/commit/736edb9c6197e23c073c98a13d484768bd6ecd79 for an example. This might be related to https://status.codecov.io/incidents/2qkxk28w0kng.

**Comment by gcotelli** [comment]
@BenBals how are you doing the integration with CodeCov? Are you just copying the token as a secret or giving it also access to the organization repositories? We have also installed the codecov GitHub app https://github.com/marketplace/codecov into our organization. Maybe this makes a difference.

**Comment by BenBals** [comment]
I have requested the codecov app be installed by the administrator, but the documentation says that the action does not need that or a token for public repos, see https://github.com/marketplace/actions/codecov (first code block).

**Comment by BenBals** [comment]
Here is more information on the issue: https://community.codecov.io/t/closed-issue-investigation-report-stuck-in-processing-unable-to-find-report-content-in-storage-archive/670/15.

**Comment by BenBals** [comment]
This has become obsolete by #148

**Pull request closed without merging**
